### ISSUE TITLE
Addon with owntone 28.6 constantly changes owntone.conf

### ISSUE THREAD

**Issue by GoSpursGoNL** [AlexanderBabel/hassio-addons#5]
## Expected Behavior
After update, still a functional library with a correct path to the music library location in owntone.conf

## Actual Behavior
After updating to 28.6, owntone.conf constantly gets modified. It reverts the path to the directory to scan to "/music", which is a folder I don't have. 
It changes it to:
directories = { "/music" }

Every time you correct it, and restart the addon, it happens again.
Restoring a backup with 28.5 and then correcting owntone.conf once works fine.
Unfortunately I can't say if this is a problem with Owntone or the addon.

**Comment by metril** [comment]
Looks like this might be a dead project

**Comment by metril** [comment]
This is a problem with the addon.

**Comment by GoSpursGoNL** [comment]
Fixed in new release, thank you @AlexanderBabel
